### ISSUE TITLE
Argument matchLevel is not set correctly when used with cy.eyesCheckWindow()

### ISSUE THREAD

**Issue by nikoll90** [applitools/eyes-cypress#17]
As stated [here](https://github.com/applitools/eyes-cypress) the matchLevel can be passed as an argument to cy.eyesCheckWindow(). But when comparing the images and when hovering over the test preview it always says "Match : Strict" although I set it to 'Layout' and the test fails. I tried using matchLevel as an argument of cy.eyesOpen() and it works as expected.

Here is some example code 
`describe('testEyes', function () {
    it('tests layout again and again some site', function () {
        cy.visit('https://www.bbc.com/')
        cy.eyesOpen({
            appName: 'Landing page',
            testName: 'Test layout',
            browser: { width: 1024, height: 768, name: 'chrome' },
        });
        cy.eyesCheckWindow({
            tag: 'TestLayout', 
            matchLevel: 'Layout'
        });
        cy.eyesClose();
    });
});`
<img width="614" alt="screen shot 2019-03-01 at 6 07 14 pm" src="https://user-images.githubusercontent.com/18418423/53650579-89967c80-3c4d-11e9-94bd-3fc55834c5ee.png">

**Comment by danielschwartz85** [comment]
Hi, thanks for noting this.
This is a documentation  error, we only support defining regions for overriding the matchLevel :

```js
    cy.eyesCheckWindow({
      strict: [ // override the general Layout matchLevel
        {top: 100, left: 0, width: 1000, height: 100},
        {selector: '.some-div-to-test-as-strict'}
      ]
    });

    cy.eyesCheckWindow({
      layout: [ // override the general Strict matchLevel
        {top: 100, left: 0, width: 1000, height: 100},
        {selector: '.some-div-to-test-as-strict'}
      ]
    });
```
(u can define a region for the entire page of course, but that would be better to set in openEyes)
cheers.
