### ISSUE TITLE
Eyes failure after each spec

### ISSUE THREAD

**Issue by gnomeontherun** [applitools/eyes-cypress#19]
My after hook tries to close eyes, but with the latest 3.6.7 it is failing.

```
  after(() => {
    cy.eyesClose();
  });
```

but every test group fails with the same message:

```[Eyes test not started] : Error: IllegalType: left is not a number

Because this error occurred during a 'after all' hook we are skipping all of the remaining tests.
      at send.then.then.body (http://localhost:4200/__cypress/tests?p=cypress/support/index.js-893:845:17)
```

It seems there is something funny coming back from Applitools or the SDK, but the actual tests run properly. This might be an upstream package problem.

If I downgrade to 3.5.6 it works fine.

**Comment by danielschwartz85** [comment]
Hi @gnomeontherun 
do u get this error while running Cypress from the cmd line or from the UI ? (If from the UI what error do u get when running from cmd line ?)

Can u share a test that reproduces the issue ?

If not - it would help if u attach the logs:
with  ```APPLITOOLS_SHOW_LOGS=true``` env variable or by adding ```showLogs:true```
to ```applitools.config.js```

Tnx.

**Comment by danielschwartz85** [comment]
closing for no response.
