### ISSUE TITLE
Batch Name does not update for subsequent uses of cy.eyesOpen()

### ISSUE THREAD

**Issue by jordancalder** [applitools/eyes-cypress#20]
I have 5 test files. In each, I call `cy.eyesOpen()` with different `batchName` options. When I check the applitools dashboard, all of the tests are under the batch name for the first test file run, not in their own separate batches. Why might this be?

**Comment by danielschwartz85** [comment]
indeed, a bug.
Tnx for raising this. 
will update 👍

**Comment by akianderson** [comment]
It looks like this might have to do with having `batchName1 defined in a global config..

**Comment by danielschwartz85** [comment]
@akianderson @jordancalder - sorry for the late response.
 Looks like it's a documentation issue.
u need tot use ``batchId``` this determines the batch
u can also use ```batchName``` this only determines the visual name your batch gets in the Applitools page.
