### ISSUE TITLE
Hardcoded Timeouts

### ISSUE THREAD

**Issue by nym** [applitools/eyes-cypress#22]
There are several hardcoded timeouts in your SDK. I'd either allow these to be configured via a param, or to honor cypress' timeouts such as taskTimeout.

**Comment by danielschwartz85** [comment]
Which timeouts exactly are u refereeing to ? (there r many timeout in the package and it's dependencies, r u against all timeout ?) what cypress timeout r u referring to ?

**Comment by danielschwartz85** [comment]
closing for irrelevancy.

**Comment by nym** [comment]
Inherit from Cypress's settings if possible.

https://docs.cypress.io/guides/references/configuration.html#Timeouts

`taskTimeout` is one of these.

**Comment by danielschwartz85** [comment]
@nym which SDK timeouts are you referring to thought ? I.e. what timeout should be changed to this ```taskTimeout``` default and why do you think it should be changed ?

the proposition is not clear..
