### ISSUE TITLE
DOCS Improvement: Instructions to handle Typescript

### ISSUE THREAD

**Issue by jordandlaman** [applitools/eyes-cypress#24]
The readme doesn't include instructions/recipes/hints on how to utilize the typescript support you added in recently.  For anyone looking into operationalizing this for an angular / cypress / typescript project I added this into my tsconfig.e2e.json that extends my projects root tsconfig

```JSON
{
 ...
  "files": ["../../node_modules/@applitools/eyes-cypress/src/setup/eyes-index.d.ts"],
  ...
}
```
Hopefully that helps anyone in the future.

**Comment by danielschwartz85** [comment]
@jordandlaman thanks for raising this.
We didn't add this to the doc because this should be done automatically when installing eyes-cypress; I.e. when running ```npx eyes-setup```  ```eyes-index.ts``` should be added to ```cypress/support/``` dir.

Can you run ```npx eyes-setup``` (again) and see if in your project setup this adds the eyes definitions correctly ?

**Comment by jordandlaman** [comment]
So that makes sense -  but my project doesn't use npx and there should at least be a reference to adding it in manually was all I was getting at.

**Comment by danielschwartz85** [comment]
I see 👍, added Typescript configuration section to the manual instruction section:
https://github.com/applitools/eyes-cypress#3-optional-typescript-configuration
