### ISSUE TITLE
Error: pollBatchEnd is not a function,  THEN {timeout: 86400000}, function(){}

### ISSUE THREAD

**Issue by nani554** [applitools/eyes-cypress#29]
Iam using simple nodejs appilcation with just cypress as my only dependency, when trying to use applitools iam facing error.

https://github.com/applitools/eyes-cypress#automatic-configuration
. Followed every step for installing and usage correctly, but still facing this error no matter which version of @applitools/eyes-cypress i use.
![image](https://user-images.githubusercontent.com/22760241/73460326-4f25ea00-439e-11ea-8f45-59dfe381e64c.png)

some.spec.js
-------------------------------
describe('Hello world', () => {
  it('works', () => {
    // cy.visit('https://applitools.com/helloworld');
    // cy.eyesOpen({
    //   appName: 'Hello World!',
    //   testName: 'My first JavaScript test!',
    //   browser: { width: 800, height: 600 },
    // });
    // cy.eyesCheckWindow('Main Page');
    // cy.get('button').click();
    // cy.eyesCheckWindow('Click!');
    // cy.eyesClose();
    cy.log('mama ek peg la')
  });
});

package.json
-------------------------

{
  "name": "cypressapplitools",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@applitools/eyes-cypress": "^3.9.7",
    "cypress": "^3.8.3"
  }
}

Note: i have even tried using applitools.config.js but of no use
applitools.config.js
---------
module.exports = {
    apiKey: 'qZTkU0HN0EIs1qPnkiohjY1030hXA3Iwl971oCNHn79AU2o110'
}

commands used: 
>> npm i @applitools/eyes-cypress -D
>> npx eyes-setup
>> set APPLITOOLS_API_KEY='qZTkU0HN0EIs1qPnkiohjY1030hXA3Iwl971oCNHn79AU2o110'
>> npx cypress open

**Comment by danielschwartz85** [comment]
Hi,
Can you share your run logs ?
```set APPLITOOLS_SHOW_LOGS=true```
Tnx.

**Comment by nani554** [comment]
I didnt do anything, after 2 days i guess opened application and ran it, iam not getting that error again, everything is fine now. Thank you for the response :)
