### ISSUE TITLE
Screenshots of React Virtualized aren't working

### ISSUE THREAD

**Issue by cdeutsch** [applitools/eyes-cypress#9]
I'm trying to use Eyes to take a screenshot of a React Virtualized Table
https://github.com/bvaughn/react-virtualized

Everything in the table is missing...

![eyes-screenshot](https://user-images.githubusercontent.com/404765/47118798-24a63100-d22e-11e8-8304-b120c645a84c.png)

It should look like this...

![regular-screenshot](https://user-images.githubusercontent.com/404765/47118805-2e2f9900-d22e-11e8-81c4-d53503c3631d.png)

I added some `console.log` to the eyes library source and it looks like it's properly parsing the DOM nodes into `cdt`...

![image](https://user-images.githubusercontent.com/404765/47119022-f70db780-d22e-11e8-82d5-58be0f973ef3.png)

...but whatever is reassembling them isn't putting them together the same.

Is there a max payload size when `sendRequest` is called?

Probably some quirk of React Virtualized but since I can't see the code on the other end that's about as far as I can take it.

I can point you to the Test Results in the Eyes GUI if need be.

**Comment by cdeutsch** [comment]
I have a hunch this is possibly a scrolling issue.

I've noticed in some other screenshots Eyes doesn't take into account what is scrolled into view in elements that have an overflow.

I wonder if it'd be possible to save the scrolling position of overflowed elements when you're parsing the DOM?

**Comment by amitzur** [comment]
Hi @cdeutsch, we're terribly sorry in responding to your issue!
We usually take no more than a day to reply...

Your analysis was indeed correct. We currently fall short on elements which scroll internally. This is a limitation we are currently discussing, and will post any updates we have to this issue.

**Comment by amitzur** [comment]
While there's indeed an issue with scrolled elements, there's no reason for the content not to render properly **even if it doesn't maintain the scroll position**.

Could you share what project you are capturing?

I rendered successfully 2 of the examples - the [list](https://bvaughn.github.io/react-virtualized/#/components/List) and [full page grid](https://rawgit.com/bvaughn/react-virtualized/master/playground/grid.html). See here:
![grid-virtualized](https://user-images.githubusercontent.com/394320/48405495-0521fb80-e73b-11e8-826f-cf5daf2fa7ff.png)
![virtualized](https://user-images.githubusercontent.com/394320/48405496-05ba9200-e73b-11e8-9835-0d98f00f4cbd.png)

**Comment by cdeutsch** [comment]
Sorry I can't share the project. 

I think the difference is mine is scrolled to the bottom on initial render instead of starting at the top.
`scrollToAlignment="end"`

Basically, if there isn't plans to support scrolling I think you can close this issue.

**Comment by amitzur** [comment]
There is a workaround that you might find helpful for this case.
We provide a way for you to specify a script that the browser will evaluate before capturing the screenshot.
So you could do something like:
```
cy.eyesCheckWindow({
  scriptHooks: {
    beforeCaptureScreenshot: 'document.querySelector(...).scrollTop = 1000'
  }
})
```
The relevant section in the docs is here: https://github.com/applitools/eyes.cypress#arguments-to-cyeyescheckwindow
